/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LandingpageImport } from './routes/landingpage'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LandingpageRoute = LandingpageImport.update({
  id: '/landingpage',
  path: '/landingpage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/landingpage': {
      id: '/landingpage'
      path: '/landingpage'
      fullPath: '/landingpage'
      preLoaderRoute: typeof LandingpageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landingpage': typeof LandingpageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landingpage': typeof LandingpageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/landingpage': typeof LandingpageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landingpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landingpage'
  id: '__root__' | '/' | '/landingpage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingpageRoute: typeof LandingpageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingpageRoute: LandingpageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/landingpage"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/landingpage": {
      "filePath": "landingpage.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
